apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    namespace: {{ .Values.namespace }}
    labels:
        app: {{  .Chart.Name }}
        chart: {{ .Chart.Name}}-{{ .Chart.Version | replace "+" "_" }}
        release: "{{ .Release.Name }}"
{{- if $.Values.secrets }}
data:
{{- range $key, $secret := $.Values.secrets }}
  {{ $key }}: {{ $secret | quote }}
{{- end }}
{{- end }}
